### ISSUE TITLE
Category Manager Page

### ISSUE THREAD

**Issue by blackcl3** [nss-evening-cohort-19/rare-client-blue-legs-2-electric-boogaloo#40] opened 2022-11-04 01:39 UTC

**Comment by lesleyjkeyes** [comment] 2022-11-05 14:59
Duplicate of [issue number 19 ](https://github.com/nss-evening-cohort-19/rare-client-blue-legs-2-electric-boogaloo/issues/19)

**Closed as completed by lesleyjkeyes** 2022-11-05 14:59 UTC
