### ISSUE TITLE
Tag Manager Page

### ISSUE THREAD

**Issue by mmccullough1997** [nss-evening-cohort-19/rare-client-blue-legs-2-electric-boogaloo#43] opened 2022-11-04 01:41 UTC

**Comment by lesleyjkeyes** [comment] 2022-11-05 15:00
Duplicate of [issue number 20](https://github.com/nss-evening-cohort-19/rare-client-blue-legs-2-electric-boogaloo/issues/20)

**Closed as completed by lesleyjkeyes** 2022-11-05 15:00 UTC
